sonar.projectKey=bannglacalender_bangla-calendar
sonar.projectName=Bangla Calendar

sonar.sources=src
sonar.tests=src/test
sonar.sourceEncoding=UTF-8

sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/test/**,src/main.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.config.*

sonar.javascript.lcov.reportPaths=coverage/lcov.info
